# Generated by Django 4.1.7 on 2023-03-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city_profile_profession_profile_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='interest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(default='https://github.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='https://linkedin.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='https://twitter.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(default='https://mysite.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube',
            field=models.CharField(default='https://youtube.com', max_length=100),
        ),
    ]
