# Generated by Django 4.1.7 on 2023-03-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['published'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
